import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/compoments/admin-layout/Header";
import Sidebar from "@/compoments/admin-layout/sidebar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>

      <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head> */}
      <body className="nk-body bg-lighter npc-default has-sidebar no-touch nk-nio-theme">
      <Toaster />
      

          {children}
        
      </body>
    </html>
  );
}
